/**
 * Supported JSON Schema property types for tool parameter definitions.
 */
export type JsonSchemaTypeName =
  'string' | 'number' | 'integer' | 'boolean' | 'array' | 'object' | 'null';

/**
 * Simplified JSON Schema property definition.
 */
export interface JsonSchemaProperty {
  readonly type: JsonSchemaTypeName;
  readonly description?: string;
  readonly enum?: readonly (string | number | boolean)[];
  readonly items?: JsonSchemaProperty;
  readonly properties?: Record<string, JsonSchemaProperty>;
  readonly required?: readonly string[];
  readonly default?: unknown;
}

/**
 * Full tool input parameters JSON schema.
 */
export interface ToolParametersSchema {
  readonly type: 'object';
  readonly properties: Record<string, JsonSchemaProperty>;
  readonly required?: readonly string[];
  readonly additionalProperties?: boolean;
}

/**
 * Declarative definition of an AI-callable tool.
 */
export interface ToolDefinition {
  readonly name: string;
  readonly description: string;
  readonly parameters: ToolParametersSchema;
  readonly isReadOnly?: boolean;
  readonly requiresConfirmation?: boolean;
}

/**
 * Invocation request generated by a model.
 */
export interface ToolCall {
  readonly id: string;
  readonly name: string;
  readonly arguments: Record<string, unknown>;
}

/**
 * Result returned following tool execution.
 */
export interface ToolResult {
  readonly callId: string;
  readonly name: string;
  readonly output: unknown;
  readonly isError?: boolean;
  readonly errorMessage?: string;
  readonly executionDurationMs?: number;
}

/**
 * Metadata and security context provided to a tool during execution.
 */
export interface ToolExecutionContext {
  readonly executionId: string;
  readonly correlationId: string;
  readonly callerId: string;
  readonly timeoutMs?: number;
  readonly cancellationSignal?: AbortSignal;
}

/**
 * Interface contract for executing a tool.
 */
export interface ToolExecutor {
  execute(call: ToolCall, context: ToolExecutionContext): Promise<ToolResult>;
}

/**
 * Error raised during tool execution or parameter validation.
 */
export class ToolExecutionError extends Error {
  public readonly toolName: string;
  public readonly callId?: string | undefined;

  constructor(message: string, toolName: string, callId?: string) {
    super(message);
    this.name = 'ToolExecutionError';
    this.toolName = toolName;
    this.callId = callId;
    Object.setPrototypeOf(this, new.target.prototype);
  }
}
