import type {
  CanonicalModelId,
  ModelInvocationParameters,
  TokenUsage,
} from '@oicunt-ai/model-types';

/**
 * Message participant role.
 */
export type MessageRole = 'system' | 'user' | 'assistant' | 'tool';

/**
 * Plain text content chunk.
 */
export interface TextPart {
  readonly type: 'text';
  readonly text: string;
}

/**
 * Multimodal image content chunk.
 */
export interface ImagePart {
  readonly type: 'image';
  readonly mimeType: 'image/png' | 'image/jpeg' | 'image/webp' | 'image/gif';
  readonly data: string; // Base64 encoded or URL
}

/**
 * Tool call requested by the model.
 */
export interface ToolCallPart {
  readonly type: 'tool_call';
  readonly id: string;
  readonly name: string;
  readonly arguments: Record<string, unknown>;
}

/**
 * Result of a tool execution fed back to the model.
 */
export interface ToolResultPart {
  readonly type: 'tool_result';
  readonly toolCallId: string;
  readonly name: string;
  readonly content: unknown;
  readonly isError?: boolean;
}

/**
 * Internal reasoning or thinking block generated by reasoning models.
 */
export interface ThinkingPart {
  readonly type: 'thinking';
  readonly thinking: string;
}

/**
 * Polymorphic content parts supported inside a message.
 */
export type MessageContentPart =
  TextPart | ImagePart | ToolCallPart | ToolResultPart | ThinkingPart;

/**
 * Canonical chat message representation.
 */
export interface ChatMessage {
  readonly role: MessageRole;
  readonly content: string | readonly MessageContentPart[];
  readonly name?: string;
  readonly metadata?: Record<string, unknown>;
}

/**
 * Normalized payload for requesting a model completion.
 */
export interface NormalizedCompletionRequest {
  readonly model: CanonicalModelId;
  readonly messages: readonly ChatMessage[];
  readonly parameters?: ModelInvocationParameters;
  readonly stream?: boolean;
  readonly tools?: readonly string[];
  readonly metadata?: Record<string, unknown>;
}

/**
 * Reasons why a model completed its generation.
 */
export type FinishReason =
  'stop' | 'length' | 'tool_calls' | 'content_filter' | 'error' | 'cancelled';

/**
 * Normalized completion response returned from the model gateway.
 */
export interface NormalizedCompletionData {
  readonly completionId: string;
  readonly model: CanonicalModelId;
  readonly message: ChatMessage;
  readonly finishReason: FinishReason;
  readonly usage: TokenUsage;
  readonly latencyMs: number;
}

/**
 * Types of Server-Sent Events (SSE) emitted during model streaming.
 */
export type StreamEventType = 'token' | 'tool_call' | 'thinking' | 'finish' | 'error';

export interface StreamTokenPayload {
  readonly delta: string;
}

export interface StreamToolCallPayload {
  readonly id: string;
  readonly name: string;
  readonly argumentChunk: string;
}

export interface StreamThinkingPayload {
  readonly delta: string;
}

export interface StreamFinishPayload {
  readonly finishReason: FinishReason;
  readonly usage: TokenUsage;
}

export interface StreamErrorPayload {
  readonly code: string;
  readonly message: string;
  readonly details?: unknown;
}

/**
 * Discriminated union of SSE events during generation streaming.
 */
export type StreamEvent =
  | { readonly event: 'token'; readonly data: StreamTokenPayload }
  | { readonly event: 'tool_call'; readonly data: StreamToolCallPayload }
  | { readonly event: 'thinking'; readonly data: StreamThinkingPayload }
  | { readonly event: 'finish'; readonly data: StreamFinishPayload }
  | { readonly event: 'error'; readonly data: StreamErrorPayload };
