import type {
  CanonicalModelId,
  ModelInvocationParameters,
  ReasoningEffortLevel,
  TokenUsage,
} from '@oicunt-ai/model-types';
import type { ChatMessage, FinishReason } from '@oicunt-ai/ai-types';

/**
 * Tool definition structure passed into the Orchestrator.
 */
export interface OrchestratorToolDefinition {
  readonly name: string;
  readonly description: string;
  readonly parameters: Record<string, unknown>;
  readonly isReadOnly?: boolean | undefined;
}

/**
 * Inbound chat execution payload received by the AI Orchestrator from product callers.
 */
export interface OrchestratorChatRequest {
  /** The user-selected OICUNT catalog model identity (e.g. 'oicunt.model.catalog-alpha'). */
  readonly model: CanonicalModelId;

  /** Multi-turn chat message history forming prompt context. Must contain at least one message. */
  readonly messages: readonly ChatMessage[];

  /** Optional system instructions to harmonize into messages. */
  readonly systemPrompt?: string | undefined;

  /** User-selected reasoning effort level ('low' | 'medium' | 'high'). */
  readonly effort?: ReasoningEffortLevel | undefined;

  /** Standard invocation hyperparameters. */
  readonly parameters?: ModelInvocationParameters | undefined;

  /** Whether client requests Server-Sent Events (SSE) streaming. Defaults to false. */
  readonly stream?: boolean | undefined;

  /** Multi-turn conversational session identifier. */
  readonly conversationId?: string | undefined;

  /** Lineage identifier for branching conversation trees. */
  readonly parentMessageId?: string | undefined;

  /** Tool definitions available for model invocation. */
  readonly tools?: readonly OrchestratorToolDefinition[] | undefined;

  /** Client-requested maximum execution duration in milliseconds. */
  readonly timeoutMs?: number | undefined;

  /** Arbitrary caller metadata passed through for tracing and auditing. */
  readonly metadata?: Record<string, unknown> | undefined;

  /** Whether reasoning/thinking data may be exposed to caller in stream/completion */
  readonly exposeReasoning?: boolean | undefined;
}

/**
 * Normalized chat completion data returned from the Orchestrator.
 */
export interface OrchestratorChatData {
  /** The generated assistant message */
  readonly message: ChatMessage;

  /** Normalized completion termination reason */
  readonly finishReason: FinishReason;

  /** Detailed token accounting for the turn */
  readonly usage: TokenUsage;

  /** The canonical model that executed the completion */
  readonly model: CanonicalModelId;

  /** The resolved semantic version executed (e.g. 'v1.0.0') */
  readonly version: string;

  /** The effective reasoning effort applied (if reasoning was utilized) */
  readonly effort?: ReasoningEffortLevel | undefined;

  /** Unique completion identifier generated by the execution layer */
  readonly completionId: string;

  /** Conversational session identifier */
  readonly conversationId?: string | undefined;

  /** Total elapsed turn execution latency in milliseconds */
  readonly turnLatencyMs: number;

  /** Estimated turn cost in USD based on Model Registry pricing tables */
  readonly estimatedCostUsd?: number | undefined;
}

/**
 * Standard HTTP response envelope for unary chat execution.
 */
export interface OrchestratorChatResponse {
  readonly success: true;
  readonly data: OrchestratorChatData;
  readonly meta: {
    readonly requestId: string;
    readonly correlationId: string;
    readonly timestamp: string;
  };
}
